export const FEATURE_PERMISSIONS = {
  // Dashboard
  DASHBOARD_PAGE: 'REPORT_VIEW',

  // POS Device Module
  POS_DEVICE_PAGE: 'POS_DEVICE_VIEW',
  POS_DEVICE_CREATE: 'POS_DEVICE_CREATE',
  POS_DEVICE_UPDATE: 'POS_DEVICE_UPDATE',
  POS_DEVICE_DELETE: 'POS_DEVICE_DELETE',
  POS_DEVICE_RESET: 'POS_DEVICE_RESET',

  // Menu Module
  MENU_PAGE: 'MENU_MANAGE',
  MENU_CREATE: 'MENU_MANAGE',
  MENU_UPDATE: 'MENU_UPDATE',
  MENU_DELETE: 'MENU_DELETE',

  // Staff Module (backend routes not yet implemented)
  STAFF_PAGE: 'STAFF_VIEW',
  STAFF_CREATE: 'STAFF_CREATE',
  STAFF_UPDATE: 'STAFF_UPDATE',
  STAFF_DELETE: 'STAFF_DELETE',

  // Report Module
  REPORT_PAGE: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Inventory Module
  INVENTORY_PAGE: 'INVENTORY_VIEW',
  INVENTORY_IMPORT: 'INVENTORY_IMPORT',
  INVENTORY_EXPORT: 'INVENTORY_EXPORT',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_MANAGE: 'INVENTORY_MANAGE',

  // Branch Module
  BRANCH_PAGE: 'BRANCH_VIEW',
  BRANCH_CREATE: 'BRANCH_CREATE',
  BRANCH_UPDATE: 'BRANCH_UPDATE',
  BRANCH_LOCK: 'BRANCH_LOCK',
  BRANCH_UNLOCK: 'BRANCH_UNLOCK',
  BRANCH_DELETE: 'BRANCH_DELETE',
  BRANCH_FORCE_DELETE: 'BRANCH_FORCE_DELETE',

  // Permission Module
  PERMISSION_PAGE: 'PERMISSION_VIEW',
  PERMISSION_ASSIGN: 'PERMISSION_ASSIGN',
} as const;

export type FeatureKey = keyof typeof FEATURE_PERMISSIONS;
export type FeaturePermission = (typeof FEATURE_PERMISSIONS)[FeatureKey];
