export const FEATURE_PERMISSIONS = {
  // Dashboard
  DASHBOARD_PAGE: 'DASHBOARD_VIEW',

  // POS Device Module
  POS_DEVICE_PAGE: 'POS_DEVICE_VIEW',
  POS_DEVICE_CREATE: 'POS_DEVICE_CREATE',
  POS_DEVICE_UPDATE: 'POS_DEVICE_UPDATE',
  POS_DEVICE_DELETE: 'POS_DEVICE_DELETE',

  // Menu Module
  MENU_PAGE: 'MENU_MANAGEMENT_VIEW',
  MENU_CREATE: 'MENU_CREATE',
  MENU_UPDATE: 'MENU_UPDATE',
  MENU_DELETE: 'MENU_DELETE',

  // Report Module
  REPORT_PAGE: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Inventory Module
  INVENTORY_PAGE: 'INVENTORY_VIEW',
  INVENTORY_IMPORT: 'INVENTORY_IMPORT',
  INVENTORY_EXPORT: 'INVENTORY_EXPORT',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_CREATE: 'INVENTORY_CREATE',
  INVENTORY_UPDATE: 'INVENTORY_UPDATE',
  INVENTORY_DELETE: 'INVENTORY_DELETE',

  // Branch Module
  BRANCH_PAGE: 'BRANCH_VIEW',
  BRANCH_CREATE: 'BRANCH_CREATE',
  BRANCH_UPDATE: 'BRANCH_UPDATE',
  BRANCH_LOCK: 'BRANCH_LOCK',
  BRANCH_UNLOCK: 'BRANCH_UNLOCK',
  BRANCH_DELETE: 'BRANCH_DELETE',
  BRANCH_FORCE_DELETE: 'BRANCH_FORCE_DELETE',

  // Permission Module
  PERMISSION_PAGE: 'PERMISSION_VIEW',
  PERMISSION_ASSIGN: 'PERMISSION_ASSIGN',

  // Billiard
  BILLIARD_TABLE_VIEW: 'BILLIARD_TABLE_VIEW',
  BILLIARD_TABLE_CREATE: 'BILLIARD_TABLE_CREATE',
  BILLIARD_TABLE_LAYOUT_EDIT: 'BILLIARD_TABLE_LAYOUT_EDIT',
  BILLIARD_SESSION_VIEW: 'BILLIARD_SESSION_VIEW',
  BILLIARD_SESSION_START: 'BILLIARD_SESSION_START',
  BILLIARD_SESSION_CHECKIN: 'BILLIARD_SESSION_CHECKIN',
  BILLIARD_SESSION_FINISH: 'BILLIARD_SESSION_FINISH',
  BILLIARD_RESERVATION_VIEW: 'BILLIARD_RESERVATION_VIEW',
  BILLIARD_RESERVATION_CREATE: 'BILLIARD_RESERVATION_CREATE',
  BILLIARD_RESERVATION_CANCEL: 'BILLIARD_RESERVATION_CANCEL',
  BILLIARD_ORDER_VIEW: 'BILLIARD_ORDER_VIEW',
  BILLIARD_ORDER_CREATE: 'BILLIARD_ORDER_CREATE',
  BILLIARD_ORDER_UPDATE: 'BILLIARD_ORDER_UPDATE',
  BILLIARD_ORDER_DELETE: 'BILLIARD_ORDER_DELETE',
  BILLIARD_ORDER_ADD_ITEM: 'BILLIARD_ORDER_ADD_ITEM',
  BILLIARD_PAY_VIEW: 'BILLIARD_PAY_VIEW',
  BILLIARD_PAY_PROCESS: 'BILLIARD_PAY_PROCESS',
  BILLIARD_REPORT_VIEW: 'BILLIARD_REPORT_VIEW',

  // Restaurant
  RESTAURANT_TABLE_VIEW: 'RESTAURANT_TABLE_VIEW',
  RESTAURANT_TABLE_CREATE: 'RESTAURANT_TABLE_CREATE',
  RESTAURANT_TABLE_UPDATE: 'RESTAURANT_TABLE_UPDATE',
  RESTAURANT_TABLE_DELETE: 'RESTAURANT_TABLE_DELETE',
  RESTAURANT_TABLE_LAYOUT_EDIT: 'RESTAURANT_TABLE_LAYOUT_EDIT',
  RESTAURANT_TABLE_TRANSFER: 'RESTAURANT_TABLE_TRANSFER',
  RESTAURANT_TABLE_MERGE: 'RESTAURANT_TABLE_MERGE',
  RESTAURANT_TABLE_SPLIT: 'RESTAURANT_TABLE_SPLIT',
  RESTAURANT_ORDER_VIEW: 'RESTAURANT_ORDER_VIEW',
  RESTAURANT_ORDER_CREATE: 'RESTAURANT_ORDER_CREATE',
  RESTAURANT_ORDER_UPDATE: 'RESTAURANT_ORDER_UPDATE',
  RESTAURANT_ORDER_DELETE: 'RESTAURANT_ORDER_DELETE',
  RESTAURANT_ORDER_ADD_ITEM: 'RESTAURANT_ORDER_ADD_ITEM',
  RESTAURANT_PAY_VIEW: 'RESTAURANT_PAY_VIEW',
  RESTAURANT_PAY_PROCESS: 'RESTAURANT_PAY_PROCESS',
} as const;

export type FeatureKey = keyof typeof FEATURE_PERMISSIONS;
export type FeaturePermission = (typeof FEATURE_PERMISSIONS)[FeatureKey];
