/**
 * Permission Groups — UI-level grouping for simplified permission assignment.
 *
 * Backend vẫn dùng permission check riêng lẻ (hasPermission('ORDER_CREATE')).
 * Group chỉ là frontend concept để gom permissions theo role.
 *
 * Khi user chọn group → auto select tất cả permissions thuộc group đó.
 * Một permission có thể thuộc nhiều group (union khi save).
 */
export interface PermissionGroup {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  permissions: string[];
}

export const PERMISSION_GROUPS: PermissionGroup[] = [
  {
    id: 'fnb_staff',
    name: 'Nhân viên F&B',
    description: 'Phục vụ đồ uống & món ăn: quản lý thực đơn, order F&B, bàn F&B',
    icon: 'UtensilsCrossed',
    color: 'blue',
    permissions: [
      'ORDER_VIEW',
      'ORDER_CREATE',
      'ORDER_UPDATE',
      'ORDER_HISTORY_VIEW',
      'MENU_VIEW',
      'MENU_CREATE',
      'MENU_UPDATE',
      'MENU_DELETE',
      'MENU_MANAGEMENT_VIEW',
      'TABLE_VIEW',
      'TABLE_CREATE',
      'TABLE_UPDATE',
      'POS_OPEN',
      'POS_CLOSE',
      'POS_CREATE_ORDER',
      'POS_CANCEL_ORDER',
      'POS_ORDER_QUEUE_VIEW',
      'POS_ORDER_QUEUE_CREATE',
    ],
  },
  {
    id: 'billiard_staff',
    name: 'Nhân viên Bi-a & Nhà hàng',
    description: 'Quản lý bàn bi-a & nhà hàng: phiên chơi, đặt bàn, gọi món, thanh toán',
    icon: 'CircleDot',
    color: 'emerald',
    permissions: [
      'BILLIARD_TABLE_VIEW',
      'BILLIARD_TABLE_CREATE',
      'BILLIARD_TABLE_UPDATE',
      'BILLIARD_SESSION_VIEW',
      'BILLIARD_SESSION_START',
      'BILLIARD_SESSION_CHECKIN',
      'BILLIARD_SESSION_FINISH',
      'BILLIARD_RESERVATION_VIEW',
      'BILLIARD_RESERVATION_CREATE',
      'BILLIARD_RESERVATION_CANCEL',
      'BILLIARD_ORDER_VIEW',
      'BILLIARD_ORDER_CREATE',
      'BILLIARD_ORDER_UPDATE',
      'BILLIARD_ORDER_DELETE',
      'BILLIARD_ORDER_ADD_ITEM',
      'BILLIARD_PAY_VIEW',
      'BILLIARD_PAY_PROCESS',
      'BILLIARD_REPORT_VIEW',
      'RESTAURANT_TABLE_VIEW',
      'RESTAURANT_TABLE_CREATE',
      'RESTAURANT_TABLE_UPDATE',
      'RESTAURANT_TABLE_LAYOUT_EDIT',
      'RESTAURANT_TABLE_TRANSFER',
      'RESTAURANT_TABLE_MERGE',
      'RESTAURANT_TABLE_SPLIT',
      'RESTAURANT_ORDER_VIEW',
      'RESTAURANT_ORDER_CREATE',
      'RESTAURANT_ORDER_UPDATE',
      'RESTAURANT_ORDER_ADD_ITEM',
      'RESTAURANT_PAY_VIEW',
      'RESTAURANT_PAY_PROCESS',
      'MENU_VIEW',
      'ORDER_VIEW',
      'POS_ORDER_QUEUE_VIEW',
    ],
  },
  {
    id: 'inventory_staff',
    name: 'Nhân viên Kho',
    description: 'Quản lý kho: nhập xuất tồn, điều chỉnh & kiểm kê nguyên liệu',
    icon: 'Package',
    color: 'amber',
    permissions: [
      'INVENTORY_VIEW',
      'INVENTORY_CREATE',
      'INVENTORY_UPDATE',
      'INVENTORY_DELETE',
      'INVENTORY_IMPORT',
      'INVENTORY_EXPORT',
      'INVENTORY_TRANSACTION_VIEW',
    ],
  },
  {
    id: 'warehouse_staff',
    name: 'Nhân viên kho',
    description: 'Dành cho nhân viên thực hiện nhập kho, xuất kho và theo dõi tồn kho',
    icon: 'Package',
    color: 'orange',
    permissions: [
      'INVENTORY_VIEW',
      'INVENTORY_IMPORT',
      'INVENTORY_EXPORT',
    ],
  },
  {
    id: 'pos_operator',
    name: 'Điều hành POS',
    description: 'Thao tác POS: mở/m đóng ca, tạo/hủy đơn, order queue, dashboard',
    icon: 'Smartphone',
    color: 'purple',
    permissions: [
      'POS_OPEN',
      'POS_CLOSE',
      'POS_CREATE_ORDER',
      'POS_CANCEL_ORDER',
      'POS_ORDER_QUEUE_VIEW',
      'POS_ORDER_QUEUE_CREATE',
      'POS_ORDER_QUEUE_UPDATE',
      'POS_ORDER_QUEUE_PAY',
      'POS_ORDER_QUEUE_DELETE',
      'POS_DEVICE_VIEW',
      'DASHBOARD_VIEW',
      'ORDER_VIEW',
    ],
  },
  {
    id: 'manager',
    name: 'Quản lý',
    description: 'Quản lý chi nhánh: báo cáo, khách hàng, ca làm việc, cài đặt',
    icon: 'Building2',
    color: 'violet',
    permissions: [
      'DASHBOARD_VIEW',
      'ORDER_VIEW',
      'ORDER_HISTORY_VIEW',
      'MENU_VIEW',
      'MENU_MANAGEMENT_VIEW',
      'INVENTORY_VIEW',
      'INVENTORY_IMPORT',
      'INVENTORY_EXPORT',
      'TABLE_VIEW',
      'TABLE_LAYOUT_EDIT',
      'REPORT_VIEW',
      'REPORT_EXPORT',
      'BRANCH_VIEW',
      'BRANCH_LOCK',
      'BRANCH_UNLOCK',
      'CUSTOMER_VIEW',
      'CUSTOMER_CREATE',
      'CUSTOMER_UPDATE',
      'SHIFT_VIEW',
      'SHIFT_CREATE',
      'SHIFT_CLOSE',
      'SETTINGS_VIEW',
      'SETTINGS_UPDATE',
      'BILLIARD_REPORT_VIEW',
      'POS_DEVICE_VIEW',
      'PERMISSION_VIEW',
      'PERMISSION_ASSIGN',
    ],
  },
  {
    id: 'system_admin',
    name: 'Quản trị hệ thống',
    description: 'Toàn quyền hệ thống: tất cả permissions quan trọng',
    icon: 'Shield',
    color: 'red',
    permissions: [
      'VIEW_AUDIT_LOG',
      'DASHBOARD_VIEW',
      'ORDER_VIEW',
      'ORDER_CREATE',
      'ORDER_UPDATE',
      'ORDER_DELETE',
      'ORDER_HISTORY_VIEW',
      'MENU_VIEW',
      'MENU_CREATE',
      'MENU_UPDATE',
      'MENU_DELETE',
      'MENU_MANAGEMENT_VIEW',
      'INVENTORY_VIEW',
      'INVENTORY_CREATE',
      'INVENTORY_UPDATE',
      'INVENTORY_DELETE',
      'INVENTORY_IMPORT',
      'INVENTORY_EXPORT',
      'INVENTORY_TRANSACTION_VIEW',
      'TABLE_VIEW',
      'TABLE_CREATE',
      'TABLE_UPDATE',
      'TABLE_DELETE',
      'TABLE_LAYOUT_EDIT',
      'BILLIARD_TABLE_VIEW',
      'BILLIARD_TABLE_CREATE',
      'BILLIARD_TABLE_UPDATE',
      'BILLIARD_TABLE_DELETE',
      'BILLIARD_TABLE_LAYOUT_EDIT',
      'BILLIARD_SESSION_VIEW',
      'BILLIARD_SESSION_START',
      'BILLIARD_SESSION_CHECKIN',
      'BILLIARD_SESSION_FINISH',
      'BILLIARD_RESERVATION_VIEW',
      'BILLIARD_RESERVATION_CREATE',
      'BILLIARD_RESERVATION_CANCEL',
      'BILLIARD_ORDER_VIEW',
      'BILLIARD_ORDER_CREATE',
      'BILLIARD_ORDER_UPDATE',
      'BILLIARD_ORDER_DELETE',
      'BILLIARD_ORDER_ADD_ITEM',
      'BILLIARD_PAY_VIEW',
      'BILLIARD_PAY_PROCESS',
      'BILLIARD_REPORT_VIEW',
      'RESTAURANT_TABLE_VIEW',
      'RESTAURANT_TABLE_CREATE',
      'RESTAURANT_TABLE_UPDATE',
      'RESTAURANT_TABLE_DELETE',
      'RESTAURANT_TABLE_LAYOUT_EDIT',
      'RESTAURANT_TABLE_TRANSFER',
      'RESTAURANT_TABLE_MERGE',
      'RESTAURANT_TABLE_SPLIT',
      'RESTAURANT_ORDER_VIEW',
      'RESTAURANT_ORDER_CREATE',
      'RESTAURANT_ORDER_UPDATE',
      'RESTAURANT_ORDER_DELETE',
      'RESTAURANT_ORDER_ADD_ITEM',
      'RESTAURANT_PAY_VIEW',
      'RESTAURANT_PAY_PROCESS',
      'REPORT_VIEW',
      'REPORT_EXPORT',
      'BRANCH_VIEW',
      'BRANCH_CREATE',
      'BRANCH_UPDATE',
      'BRANCH_DELETE',
      'BRANCH_LOCK',
      'BRANCH_UNLOCK',
      'BRANCH_FORCE_DELETE',
      'POS_OPEN',
      'POS_CLOSE',
      'POS_CREATE_ORDER',
      'POS_CANCEL_ORDER',
      'POS_ORDER_QUEUE_VIEW',
      'POS_ORDER_QUEUE_CREATE',
      'POS_ORDER_QUEUE_UPDATE',
      'POS_ORDER_QUEUE_DELETE',
      'POS_ORDER_QUEUE_PAY',
      'POS_DEVICE_VIEW',
      'POS_DEVICE_CREATE',
      'POS_DEVICE_UPDATE',
      'POS_DEVICE_DELETE',
      'SHIFT_VIEW',
      'SHIFT_CREATE',
      'SHIFT_UPDATE',
      'SHIFT_CLOSE',
      'CUSTOMER_VIEW',
      'CUSTOMER_CREATE',
      'CUSTOMER_UPDATE',
      'CUSTOMER_DELETE',
      'PERMISSION_VIEW',
      'PERMISSION_ASSIGN',
      'PERMISSION_MANAGE',
      'SETTINGS_VIEW',
      'SETTINGS_UPDATE',
    ],
  },
];
